### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by kaspervandenberg** [lispgames/cl-ecs#5]
I would like to use CL-ECS in [my game](https://github.com/kaspervandenberg/merlin).  Am I permitted to do so? if yes, under what license?

*(Note I was already using CL-ECS assuming it was permitted; today, when I published my sources via github, I noticed CL-ECS does not have a license.  If I'm not allowed to use CL-ECS, I will remove the dependencies.  If you decide to licence CL-ECS under a stricter licence than what my game is using, I will re-licence the game under a compatible license.)*

**Comment by mfiano** [comment]
the .asd file mentions it is the same license as your game. :)
